### ISSUE TITLE
scs plugin and zowe v2 / zowe vnext

### ISSUE THREAD

**Issue by kraabrsg** [zowe/zowe-cli-scs-plugin#59]
Hi,

i would like to do a fresh install of zowe v2 lts packages (portable install of npm/nodejs and zowe cli).
I noticed that here is no scs plugin included(in the zowe cli package like e.g 1.27.0)? 

https://www.zowe.org/download.html

Is there a *,tgz file available? We would like to do an offline installation.
I found V4.1.7 but this seems to be for zowe v1...

I allready got the npm7-bundled-dep-issue-1.0.0.tgz file as we want to use the newest node/npm lts version (16.13.2)

Thank you!

**Comment by t1m0thyj** [comment]
The reason why there is no SCS plug-in included for Zowe v2 is because the SCS plug-in has been merged into core CLI, so that Zowe CLI in v2 is secure by default without any plug-ins required.

If you download the CLI vNext preview from zowe.org using the button below, you'll get this version of Zowe CLI with the SCS built-in:
![image](https://user-images.githubusercontent.com/22344007/152194192-a12411d7-0286-4d4f-b36e-080940a9b574.png)

**Comment by kraabrsg** [comment]
Hi @t1m0thyj thanks, tried it installs like expected, thanks!
